dv_test:
  outputs:
    dev:
      account: vj61498.eu-west-3.aws
      database: DV_TEST_DB
      password: "{{ env_var('DBT_PASSWORD')}}"
      role: SYSADMIN
      schema: DV_TEST_DEV
      threads: 1
      type: snowflake
      user: "{{ env_var('DBT_USER')}}"
      warehouse: DV_TEST_WH
    ci:
      account: vj61498.eu-west-3.aws
      database: DV_TEST_DB
      password: "{{ env_var('DBT_PASSWORD')}}"
      role: SYSADMIN
      schema: DV_TEST_CI
      threads: 1
      type: snowflake
      user: "{{ env_var('DBT_USER')}}"
      warehouse: DV_TEST_WH
    prod:
      account: vj61498.eu-west-3.aws
      database: DV_TEST_DB
      password: "{{ env_var('DBT_PASSWORD')}}"
      role: SYSADMIN
      schema: DV_TEST_PROD
      threads: 1
      type: snowflake
      user: "{{ env_var('DBT_USER')}}"
      warehouse: DV_TEST_WH
  target: dev