version: 2

sources:
  - name: snowflake_sample
    database: SNOWFLAKE_SAMPLE_DATA
    schema: TPCH_SF{{ var('snowflake_sample_size', 10) }}
    tables:
      - name: LINEITEM
      - name: CUSTOMER
      - name: ORDERS
      - name: PARTSUPP
      - name: SUPPLIER
      - name: PART
      - name: NATION
      - name: REGION
